from PyQt5 import QtCore, QtGui, QtWidgets


class LK_window(QtWidgets.QDialog):
    def __init__(self, root):
        self.root = root
        super(LK_window, self).__init__()
        self.setupUi()

    def setupUi(self):
        self.setObjectName("Form")
        self.setEnabled(True)
        self.resize(456, 456)
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(40, 30, 131, 171))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setGeometry(QtCore.QRect(280, 50, 61, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self)
        self.label_3.setGeometry(QtCore.QRect(250, 100, 120, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self)
        self.label_4.setGeometry(QtCore.QRect(200, 155, 230, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self)
        self.label_5.setGeometry(QtCore.QRect(230, 200, 171, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self)
        self.label_6.setGeometry(QtCore.QRect(280, 170, 51, 30))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self)
        self.label_7.setGeometry(QtCore.QRect(280, 120, 51, 30))
        self.label_7.setFont(font)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self)
        self.label_8.setGeometry(QtCore.QRect(270, 70, 81, 30))
        self.label_8.setFont(font)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self)
        self.label_9.setGeometry(QtCore.QRect(280, 220, 51, 30))
        self.label_9.setFont(font)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setObjectName("label_9")
        self.pushButton = QtWidgets.QPushButton(self)
        self.pushButton.setGeometry(QtCore.QRect(270, 410, 160, 28))
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(self)
        self.comboBox.setGeometry(QtCore.QRect(20, 410, 140, 28))
        self.comboBox.setObjectName("comboBox")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "фото юзера"))
        self.label_2.setText(_translate("Form", "Ваш логин:"))
        self.label_3.setText(_translate("Form", "Совершено покупок:"))
        self.label_4.setText(_translate("Form", "Сумма которая была потрачена на покупки:"))
        self.label_5.setText(_translate("Form", "Количество купленного товара:"))
        self.label_6.setText(_translate("Form", "10000"))
        self.label_7.setText(_translate("Form", "10000"))
        self.label_8.setText(_translate("Form", "asikpro13"))
        self.label_9.setText(_translate("Form", "10000"))
        self.pushButton.setText(_translate("Form", "Назначить администратора"))
