# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem
from DataBase.workFromDB import db


class shopWindow(QtWidgets.QWidget):
    def __init__(self, root):
        super(shopWindow, self).__init__()
        self.root = root  # Создаем экземпляр родительского окна
        self.id = root.id.text()  # Получаем параметр админ/не админ от родительского окна
        self.resize(869, 746)  # Изменяем размер окна
        self.setMinimumWidth(self.width())  # Изменяем минимальную ширину окна
        self.setMinimumHeight(self.height())  # Изменяем минимальную высоту окна
        self.buttonForLK = QtWidgets.QPushButton(self)  # Создаем кнопку для личного кабинета
        self.buttonForAddProduct = QtWidgets.QPushButton(self)  # Создаем кнопку для добавления продукта(only admin)
        self.buttonForDelProduct = QtWidgets.QPushButton(self)  # Создаем кнопку для удаления продукта(only admin)
        if self.id == '0':  # Если пользователь не админ то скрываем от него кнопки добавления и удаления продукта
            self.buttonForAddProduct.hide()
            self.buttonForDelProduct.hide()
        self.buttonForCreateCheck = QtWidgets.QPushButton(self)  # Создаем кнопку для выписки чек
        self.lineEditForSearch = QtWidgets.QLineEdit(self)  # Создаем поле для поиска
        self.tableWidget = QtWidgets.QTableWidget(self)  # Создаем таблицу
        self.label = QtWidgets.QLabel(self)  # Создаем лейбл(для текста)
        self.setupUi()  # Вызов метода с основной работой

    def setupUi(self):  # Основной метод
        #  Все кнопки создаются по мере работы, а не в инициализации т.к. после инициализации кнопки не хотят работать
        self.setObjectName("Form")
        self.buttonForLK.setGeometry(QtCore.QRect(730, 30, 120, 28))
        self.buttonForLK.setObjectName("pushButton")
        self.buttonForLK.clicked.connect(self.addProductWindow)
        self.buttonForAddProduct.setGeometry(QtCore.QRect(20, 30, 131, 28))
        self.buttonForAddProduct.setObjectName("pushButton_2")
        self.buttonForDelProduct.setGeometry(QtCore.QRect(260, 30, 130, 28))
        self.buttonForDelProduct.setObjectName("pushButton_5")
        self.buttonForCreateCheck.setGeometry(QtCore.QRect(510, 30, 110, 28))
        self.buttonForCreateCheck.setObjectName("pushButton_6")
        self.lineEditForSearch.setGeometry(QtCore.QRect(160, 80, 690, 22))
        self.lineEditForSearch.setObjectName("lineEdit")
        self.tableWidget.setGeometry(QtCore.QRect(20, 110, 831, 621))
        self.tableWidget.resize(831, 621)  # изменяем размер таблицы
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setHorizontalHeaderItem(0, QtWidgets.QTableWidgetItem('ID'))
        self.tableWidget.setHorizontalHeaderItem(1, QtWidgets.QTableWidgetItem('ФОТО'))
        self.tableWidget.setHorizontalHeaderItem(2, QtWidgets.QTableWidgetItem('БРЕНД'))
        self.tableWidget.setHorizontalHeaderItem(3, QtWidgets.QTableWidgetItem('НАЗВАНИЕ'))
        self.tableWidget.setHorizontalHeaderItem(4, QtWidgets.QTableWidgetItem('ЦЕНА'))
        self.tableWidget.setHorizontalHeaderItem(5, QtWidgets.QTableWidgetItem('КОЛИЧЕСТВО'))
        self.updateTable()
        self.label.setGeometry(QtCore.QRect(30, 80, 120, 20))
        self.label.setObjectName("label")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Касса"))
        self.buttonForLK.setText(_translate("Form", "Личный кабинет"))
        self.buttonForAddProduct.setText(_translate("Form", "Добавить продукт"))
        self.buttonForDelProduct.setText(_translate("Form", "удалить продукт"))
        self.buttonForCreateCheck.setText(_translate("Form", "Выписать чек"))
        self.label.setText(_translate("Form", "Поиск продукта:"))

    def addProductWindow(self):
        pass

    def updateTable(self):
        res = db('select * from product')
        for i, row in enumerate(res):
            self.tableWidget.setRowCount(
                self.tableWidget.rowCount() + 1)
            for j, elem in enumerate(row):
                self.tableWidget.setItem(i, j, QTableWidgetItem(str(elem)))

    def resizeEvent(self, Event):
        self.tableWidget.resize(self.width() - (self.width() // 100 * 5), self.height() - (self.height() // 100 * 5) - self.tableWidget.y() + 20)
        self.tableWidget.move(self.width() // 2 - self.tableWidget.width() // 2, self.tableWidget.y())
        self.lineEditForSearch.resize(self.width() - (self.width() // 100 * 5) - 140, self.lineEditForSearch.height())
        self.lineEditForSearch.move(self.width() // 2 - self.lineEditForSearch.width() // 2 + 70, self.lineEditForSearch.y())